shell fix

diff --git a/bin/camoo b/bin/camoo
--- a/bin/camoo
+++ b/bin/camoo
@@ -5,48 +5,44 @@
 #
 # -------------------------------------------------------------------------
 
-VARIABLE=$@
+VARIABLE=$*
 
 if [ -z "$VARIABLE" ]; then
-	echo "Parameter is missing"
-	exit 0
+  echo "Parameter is missing"
+  exit 0
 fi
 
 getShellDir() {
-	NAME="$1"
-	if [ -f "$NAME" ]
-	then
-		DIR=$(dirname -- "$NAME")
-		NAME=$(cd -P "$DIR" > /dev/null && pwd -P)/$(basename -- "$NAME")
-	fi
-	while [ -h "$NAME" ]; do
-		DIR=$(dirname -- "$NAME")
-		SYM=$(readlink "$NAME")
-		NAME=$(cd "$DIR" > /dev/null && cd $(dirname -- "$SYM") > /dev/null && pwd)/$(basename -- "$SYM")
-	done
-	echo "$NAME"
+  NAME="$1"
+  if [ -f "$NAME" ]; then
+    DIR=$(dirname -- "$NAME")
+    NAME=$(cd -P "$DIR" >/dev/null && pwd -P)/$(basename -- "$NAME")
+  fi
+  while [ -h "$NAME" ]; do
+    DIR=$(dirname -- "$NAME")
+    SYM=$(readlink "$NAME")
+    NAME=$(cd "$DIR" >/dev/null && cd $(dirname -- "$SYM") >/dev/null && pwd)/$(basename -- "$SYM")
+  done
+  echo "$NAME"
 }
 
-IN_PHP=( php php7.2 php7.3 php7.4 php8.0 )
+IN_PHP=(php php7.2 php7.3 php7.4 php8.0)
 php_cli() {
-	for php in "${IN_PHP[@]}"
-	do
-		SAPI=`echo "<?= PHP_SAPI ?>" | $php 2>/dev/null`
-		if [ "$SAPI" = "cli" ]
-		then
-			echo $php
-			return
-		fi
-	done
-	echo "Failed to find a CLI version of PHP; falling back to system standard php executable" >&2
-	echo "php";
+  for php in "${IN_PHP[@]}"; do
+    SAPI=$(echo "<?= PHP_SAPI ?>" | $php 2>/dev/null)
+    if [ "$SAPI" = "cli" ]; then
+      echo "$php"
+      return
+    fi
+  done
+  echo "Failed to find a CLI version of PHP; falling back to system standard php executable" >&2
+  echo "php"
 }
 
 # If current path is a symlink, resolve to real path
 realname="$0"
-if [ -L "$realname" ] 
-then
-	realname=$(readlink -f "$0")
+if [ -L "$realname" ]; then
+  realname=$(readlink -f "$0")
 fi
 
 SHELL=$(dirname -- "$(getShellDir "$realname")")
@@ -54,37 +50,43 @@ APP=$(dirname "$SHELL")
 
 # variable with the correct path in it.
 if [ -z "$PHP" ]; then
-	PHP=$(php_cli)
+  PHP=$(php_cli)
 fi
 
 if [ "$VARIABLE" == "cleanup:core" ]; then
-	echo "Clear Core cache..."
-	rm -rf $APP/tmp/cache/persistent/persistent/*
-	echo "[DONE]"
-	exit 0
+  echo "Clear Core cache..."
+  rm -rf "$APP"/tmp/cache/persistent/persistent/*
+  echo "[DONE]"
+  exit 0
 fi
 
 if [ "$VARIABLE" == "cleanup:tpl" ]; then
-	echo "Clear Template's cache..."
-	rm -rf $APP/tmp/cache/tpl/*
-	echo "[DONE]"
-	exit 0
+  echo "Clear Template's cache..."
+  rm -rf "$APP"/tmp/cache/tpl/*
+  echo "[DONE]"
+  exit 0
+fi
+
+if [ "$VARIABLE" == "cleanup:tariff" ]; then
+  echo "Clear Tariff cache..."
+  rm -rf "$APP"/tmp/cache/persistent/tariff/*
+  echo "[DONE]"
+  exit 0
 fi
 
 if [ "$VARIABLE" == "cleanup:all" ]; then
-	echo "Clear ALL caches..."
-	rm -rf $APP/tmp/cache/persistent/persistent/*
-	rm -rf $APP/tmp/cache/tpl/*
-	echo "[DONE]"
-	exit 0
+  echo "Clear ALL caches..."
+  rm -rf "$APP"/tmp/cache/persistent/persistent/*
+  rm -rf "$APP"/tmp/cache/tpl/*
+  rm -rf "$APP"/tmp/cache/persistent/tariff/*
+  echo "[DONE]"
+  exit 0
 fi
 
-
-if [ $(basename $realname) != 'camoo' ]
-then
-	exec $PHP "$SHELL"/camoo.php $(basename $realname) "$@"
+if [ "$(basename "$realname")" != 'camoo' ]; then
+  exec "$PHP" "$SHELL"/camoo.php "$(basename "$realname")" "$@"
 else
-	exec $PHP "$SHELL"/camoo.php "$@"
+  exec "$PHP" "$SHELL"/camoo.php "$@"
 fi
 
 exit 0
